name: Generate Snake

on:
  schedule:
    # Ejecutar automáticamente una vez al día
    - cron: "0 0 * * *" # Este cronjob se ejecuta cada día a la medianoche
  workflow_dispatch: # Permite ejecutar manualmente desde la pestaña de "Actions"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Descarga el código del repositorio
      - name: Checkout
        uses: actions/checkout@v3 # Usa la última versión disponible

      # Generar la animación de la serpiente
      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3 # Usa la última versión disponible
        with:
          github_user_name: JulianKer
          outputs: snake.svg # Guardar en la raíz del repositorio

      # Subir el archivo generado al repositorio (en la raíz)
      - name: Commit and push if updated
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add snake.svg # Guardar el archivo directamente en la raíz
          git commit -m "Generated snake" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
